version: '3.8'

services:
  # MariaDB service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser123
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - wordpress-network

  # WordPress service
  wordpress:
    image: wordpress:6.3.1-php8.2-fpm
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbuser123
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wordpress-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - certbot-etc:/etc/letsencrypt
    depends_on:
      - wordpress
    networks:
      - wordpress-network
      
  # certbot:
  #   depends_on:
  #     - nginx
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress-data:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email jan@benekiva.com --agree-tos --no-eff-email --force-renewal -d staging2.benekiva.com

volumes:
  # certbot-etc:
  wordpress-data:
  mariadb-data:

networks:
  wordpress-network:
